name: Run Tests

on: [push, pull_request]

jobs:
  test:
    name: Test on Node ${{ matrix.node }} on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Lint
        run: npm run lint

      - name: Test with Coverage
        run: npm run test

      - name: Publish on Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ matrix.node }}
          parallel: true

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
  
  publish:
    needs: report-coverage
    runs-on: ubuntu-latest
    steps:
      - name: Show ref
        run: echo ${{ github.ref }}